name: mentor_codetivate_hackathon
description: The project is built using Flutter for web for the 2021 codetivate hackathon. The  project showcases the power of flutter un UI design and it includes intergration with Firebase for authentication and data storage
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/gui/facebook.png
    - assets/gui/github.png
    - assets/gui/instagram.png
    - assets/gui/intro_image.png
    - assets/gui/linkedin.png
    - assets/gui/logo.png
    - assets/gui/twitter.png
    - assets/gui/world.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Fugaz One
      fonts:
        - asset: assets/fonts/Fugaz_One/FugazOne-Regular.ttf